spring.application.name=spring-cloud-config-server
spring.cloud.config.server.git.uri=file:///Users/yahia.tarek/Downloads/demo
server.port=8888
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans
